name = "papa-bob-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "papa-bob-photos"

[[d1_databases]]
binding = "DB"
database_name = "papa-bob-db"
database_id = "797d1768-5996-45ce-aa77-07f67d28c220"

[vars]
MAGIC_WORD = "LoveYou"

[[routes]]
pattern = "papabob.org/api/*"
zone_name = "papabob.org"
